const { runInInitedProject } = require('./run')

describe('init command', () => {
  it('should create e2e-tests/nightwatch/ directory', async () => {
    const { fs } = await runInInitedProject('nightwatch:add')

    expect(fs.existsSync('/e2e-tests/nightwatch')).toBe(true)
  })

  it('should create .gitignore', async () => {
    const { fs } = await runInInitedProject('nightwatch:add')

    // expect(fs.readFileSync('/e2e-tests/.gitignore', { encoding: 'utf8' })).toMatchInlineSnapshot(`
    //   "node_modules/
    //   .env

    //   # Autogenerated files
    //   tests_output/
    //   mochawesome-report/
    //   *.log
    //   package-lock.json
    //   "
    // `)
  })
})
