const { Volume, createFsFromVolume } = require('memfs')
const yargs = require('yargs')
const { main } = require('../src')

/**
 *
 * @param {string} cmd command to run
 * @returns {Promise<{ fs: import('fs') }>}
 */
async function run(cmd) {
  yargs.reset()

  /** @type {any} */
  const fs = createFsFromVolume(new Volume())
  process.chdir('/')

  main({
    yargs: yargs(['/bin/node', '/bin/eto']),
    fs,
  })

  yargs.parse(cmd)

  return { fs }
}

describe('init command', () => {
  it('should create e2e-tests/ directory', async () => {
    const { fs } = await run('init')

    expect(fs.existsSync('/e2e-tests')).toBe(true)
  })

  it('should create .gitignore', async () => {
    const { fs } = await run('init')

    expect(fs.readFileSync('/e2e-tests/.gitignore', { encoding: 'utf8' })).toMatchInlineSnapshot(`
      "node_modules/
      .env

      # Autogenerated files
      tests_output/
      mochawesome-report/
      *.log
      package-lock.json
      "
    `)
  })
})
