const path = require('path')
const {
  getConfig,
  updateJsonFile,
  updateToolConfig,
  getTestsRootDir,
  getParentProjectPackageJsonSafe,
  validatePackageName,
  createFilesFromTemplates,
  getProjectRootDir,
} = require('@csssr/e2e-tools/utils')
const packageName = require('../package.json').name

function createToolConfig() {
  return {
    browsers: {
      local_chrome: {
        default: true,
        type: 'webdriver',
        desiredCapabilities: {
          browserName: 'chrome',
          'goog:chromeOptions': {
            args: ['--window-size=1200,800'],
          },
        },
        globals: {
          skipScreenshotAssertions: true,
        },
      },
      remote_chrome: {
        remote: true,
        type: 'selenium',
        url: 'https://chrome.selenium.csssr.cloud',

        basicAuth: {
          credentialsId: 'chromedriver',
          username_env: 'CHROMEDRIVER_USERNAME',
          password_env: 'CHROMEDRIVER_PASSWORD',
        },

        desiredCapabilities: {
          browserName: 'chrome',
          'goog:chromeOptions': {
            w3c: false,
            args: ['--headless', '--no-sandbox', '--disable-gpu', '--window-size=1200,800'],
          },
        },
        globals: { skipScreenshotAssertions: false },
      },
    },
  }
}

function normalizeUrl(input) {
  if (input.startsWith('http')) {
    return input
  }

  return `http://${input}`
}

function falseToError(error, func) {
  return (str) => (func(str) ? true : error)
}

async function initScript({ inquirer }) {
  const parentProjectPackageJson = getParentProjectPackageJsonSafe() || {}

  async function prompt(question) {
    const answers = await inquirer.prompt([question])

    return answers[question.name]
  }
  const config = getConfig()

  const launchUrl = await prompt({
    type: 'input',
    name: 'launchUrl',
    default: config.defaultLaunchUrl,
    message: 'Адрес стенда по умолчанию',
  })

  const projectName = await prompt({
    type: 'input',
    name: 'projectName',
    default: config.projectName || parentProjectPackageJson.name,
    message: 'Название проекта (маленькими буквами без пробелов)',
    validate: falseToError('Навалидное название пакета', validatePackageName),
  })

  const configNewFields = {
    projectName,
    defaultLaunchUrl: normalizeUrl(launchUrl),
  }

  updateJsonFile({
    filePath: path.join(getTestsRootDir(), 'e2e-tools.json'),
    update(prevConfig) {
      return {
        ...prevConfig,
        ...configNewFields,
      }
    },
  })

  createFilesFromTemplates({
    templatesGlob: '**/*.hbs',
    templatesData: {
      config: { ...config, ...configNewFields },
    },
    templatesRoot: path.join(__dirname, '../templates'),
    destinationRoot: getProjectRootDir(),
  })

  updateToolConfig(packageName, createToolConfig)

  updateVsCodeTasks()
}

function upgrade() {
  createFilesFromTemplates({
    templatesGlob: '**/*.autogenerated.hbs',
    templatesData: { config: getConfig() },
    templatesRoot: path.join(__dirname, '../templates'),
    destinationRoot: getProjectRootDir(),
  })

  updateVsCodeTasks()
  upgradeRemoteBrowsersConfig()
}

module.exports = {
  getCommands,
  initScript,
  upgrade,
}
