FROM node:8

WORKDIR /usr/src/app

COPY ../package.json ../yarn.lock ./
RUN yarn install --frozen-lockfile && yarn cache clean

COPY . ./nightwatch

RUN touch .env

ENTRYPOINT yarn et nightwatch:run --browser remote_chrome
