const path = require('path')
const spawn = require('cross-spawn')
const getPackageInfo = require('package-info')
const {
  getTestsRootDir,
  getProjectRootDir,
  updateJsonFile,
  getConfigSafe,
  getConfig,
  createFilesFromTemplates,
} = require('./utils')
const toolsPackageInfo = require('../package.json')

// const initCommand = ({ config }) => ({
//   command: 'init',
//   describe: 'Setup tests in current project',
//   handler() {
//     if (path.basename(process.cwd()) === 'e2e-tests') {
//       throw new Error('Already inited')
//     }

//     createFilesFromTemplates({
//       templatesGlob: '**/*.hbs',
//       templatesData: { toolsVersion: config.version },
//       templatesRoot: path.join(__dirname, '../templates'),
//       destinationRoot: getProjectRootDir(),
//     })

//     spawn.sync('yarn', ['install'], {
//       stdio: 'inherit',
//       cwd: getTestsRootDir(),
//     })
//   },
// })

const addToolCommand = ctx => ({
  command: 'add-tool <package-name>',
  describe: 'Add new tool',
  handler({ packageName }) {
    updateJsonFile(ctx, {
      filePath: path.join(getTestsRootDir(ctx), 'e2e-tools.json'),
      update(config) {
        return {
          ...config,
          tools: {
            ...config.tools,
            [packageName]: true,
          },
        }
      },
    })

    // spawn.sync('yarn', ['add', '--dev', '--tilde', packageName], {
    //   stdio: 'inherit',
    //   cwd: getTestsRootDir(),
    // })
    ctx.yarn.addPackage(packageName)

    // spawn.sync('yarn', ['install'], {
    //   stdio: 'inherit',
    //   cwd: getTestsRootDir(),
    // })
    ctx.yarn.install()

    const tool = require(packageName)

    tool.initScript(ctx).catch(console.error)
  },
})

async function updateTool(packageName, context) {
  spawn.sync('yarn', ['add', '--dev', '--tilde', `${packageName}@latest`], {
    stdio: 'inherit',
    cwd: getTestsRootDir(),
  })

  const tool = require(packageName)

  if (tool.upgrade) {
    await tool.upgrade(context)
  }
}

const upgradeCommand = context => ({
  command: 'upgrade',
  describe: 'Upgrades all packages',
  async handler() {
    const info = await getPackageInfo(toolsPackageInfo.name)

    if (toolsPackageInfo.version !== info.version) {
      spawn.sync('yarn', ['add', '--dev', '--tilde', `${toolsPackageInfo.name}@latest`], {
        stdio: 'inherit',
        cwd: getTestsRootDir(),
      })

      // Если прошло обновление основного пакета, запускаем новую версию кода и выходим
      spawn.sync('yarn', ['et', 'upgrade'], {
        stdio: 'inherit',
        cwd: getTestsRootDir(),
      })

      process.exit(0)
      return
    }

    createFilesFromTemplates({
      templatesGlob: '**/*.autogenerated.hbs',
      templatesData: { toolsVersion: context.config.version },
      templatesRoot: path.join(__dirname, '../templates'),
      destinationRoot: getProjectRootDir(),
    })

    const config = getConfig()
    if (!config.tools) {
      return
    }

    const toolNames = Object.keys(config.tools)

    for (const toolName of toolNames) {
      await updateTool(toolName, context)
    }

    spawn.sync('yarn', ['install'], {
      stdio: 'inherit',
      cwd: getTestsRootDir(),
    })
  },
})

function initCommand1(ctx) {
  return {
    command: 'init',
    describe: 'Setup tests in current project',
    handler() {
      if (path.basename(ctx.cwd) === 'e2e-tests') {
        throw new Error('Already inited')
      }

      createFilesFromTemplates(ctx, {
        templatesGlob: '**/*.hbs',
        // templatesData: { toolsVersion: config.version },
        templatesData: { toolsVersion: ctx.version },
        templatesRoot: path.join(__dirname, '../templates'),
        destinationRoot: getProjectRootDir(ctx),
      })

      // spawn.sync('yarn', ['install'], {
      //   stdio: 'inherit',
      //   cwd: getTestsRootDir(),
      // })

      ctx.yarn.install({
        // cwd: getTestsRootDir(),
      })
    },
  }
}

exports.main = ctx => {
  ctx.yargs
    .command(initCommand1(ctx))
    .command(addToolCommand(ctx))
    .demandCommand()
    .help().argv

  // process.chdir(getTestsRootDir())
  // const config = getConfigSafe()
  // context.yargs
  //   .command(addToolCommand(context))
  //   .command(initCommand(context))
  //   .command(upgradeCommand(context))
  // if (config && config.tools) {
  //   Object.keys(config.tools).forEach(toolName => {
  //     const tool = require(toolName)
  //     if (typeof tool.getCommands === 'function') {
  //       tool.getCommands(context).forEach(command => {
  //         context.yargs.command(command)
  //       })
  //     }
  //   })
  // }
  // context.yargs.demandCommand().help().argv
}
