name: Lint
on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Lint with prettier
        run: |
          prettierVersion="$(cat package.json | jq .devDependencies.prettier -r)"
          npx --package "prettier@$prettierVersion" prettier --check .
