name: publish
on:
  push:
    branches:
      - master
      - canary

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Fetch all git history
        run: git fetch --prune --unshallow

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Configure git
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"

      - name: Build testcafe-browser-provider-csssr module
        run: make build
        working-directory: ./modules/testcafe-browser-provider-csssr

      - name: Publish prerelease
        run: |
          yarn lerna publish --yes --canary --force-publish --no-verify-access
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        if: github.ref == 'refs/heads/canary'

      - name: Up version in package.json and create github release
        run: yarn lerna version --conventional-commits --conventional-graduate --allow-branch=master --yes --create-release github
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.ref == 'refs/heads/master'

      - name: Publish release to npm
        run: yarn lerna publish from-package --yes --no-verify-access
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        if: github.ref == 'refs/heads/master'

      - name: Create .npmrc for github registry auth
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: 'https://npm.pkg.github.com'
          cache: yarn
        if: github.ref == 'refs/heads/master'

      - name: Publish release to GitHub registry
        run: yarn lerna publish from-package --yes --registry https://npm.pkg.github.com/CSSSR
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.ref == 'refs/heads/master'
